#!/bin/bash

set -e

VERSION_TO_BUILD=$(cat version_to_build)

mkdir -p $GOPATH/src/code.cloudfoundry.org
cd $GOPATH/src/code.cloudfoundry.org

git clone https://github.com/cloudfoundry/cli

cd cli

git checkout v${VERSION_TO_BUILD}

BUILD_VERSION=$(cat ci/VERSION)
BUILD_SHA=$(git rev-parse --short HEAD)
BUILD_DATE=$(date -u +"%Y-%m-%d")

BINARY=out/cf_${BUILD_VERSION}_${BUILD_DATE}

GOARCH=arm \
GOOS=linux \
  go build \
    -ldflags "-extldflags '-static' -X code.cloudfoundry.org/cli/version.binaryVersion=${BUILD_VERSION} -X code.cloudfoundry.org/cli/version.binarySHA=${BUILD_SHA} -X code.cloudfoundry.org/cli/version.binaryBuildDate=${BUILD_DATE}" \
    -o $BINARY

file $BINARY

aws s3 cp $BINARY s3://cf-cli-pi

aws s3 ls cf-cli-pi | awk '{sub(".*","<a href=\"&\">&</a>",$4); print}' > index.html

aws s3 cp index.html s3://cf-cli-pi
