#!/bin/bash

git clone https://github.com/cloudfoundry/cli

cd cli

git checkout v$(cat ../version_to_build)

BUILD_VERSION=$(cat ci/VERSION)
BUILD_SHA=$(git rev-parse --short HEAD)
BUILD_DATE=$(date -u +"%Y-%m-%d")

GOARCH=arm \
GOOS=linux \
  go build \
    -ldflags "-extldflags '-static' -X code.cloudfoundry.org/cli/version.binaryVersion=${BUILD_VERSION} -X code.cloudfoundry.org/cli/version.binarySHA=${BUILD_SHA} -X code.cloudfoundry.org/cli/version.binaryBuildDate=${BUILD_DATE}" \
    -o ../cf-cli_linux_arm

file !$
